
repo_keyalias: runnervmlun5p.zvdvyfcjeymexeylymndxtzdia.yx.internal.cloudapp.net


keydname: CN=runnervmlun5p.zvdvyfcjeymexeylymndxtzdia.yx.internal.cloudapp.net, OU=F-Droid


keystorepass: 2k+N5nKATbgw5UTiQf5/GQ9XVCdLgPuTfDEzNeVKZ4o=


keypass: 2k+N5nKATbgw5UTiQf5/GQ9XVCdLgPuTfDEzNeVKZ4o=

